apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv
spec:
    storageClassName: localstorage
    capacity:
      storage: 4Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/data/"